DROP TABLE IF EXISTS notes CASCADE;
CREATE TABLE notes (
  id SERIAL PRIMARY KEY NOT NULL,
  title VARCHAR(255) DEFAULT 'New Note' NOT NULL,
  content TEXT,
  notebook_id INTEGER REFERENCES notebooks(id) ON DELETE CASCADE,
  created_at TIMESTAMP DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMP DEFAULT NOW() NOT NULL
);